<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketMind.Data.Common\MarketMind.Data.Common.csproj" />
    <ProjectReference Include="..\MarketMind.Data\MarketMind.Data.csproj" />
    <ProjectReference Include="..\MarketMind.Models\MarketMind.Data.Models.csproj" />
    <ProjectReference Include="..\MarketMind.Web.ViewModels\MarketMind.Web.ViewModels.csproj" />
  </ItemGroup>

</Project>
