<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-MarketMind-ef5035ba-4787-46f5-8d1e-a9f5c2d5c9b1</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.22" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MarketMind.Data\MarketMind.Data.csproj" />
    <ProjectReference Include="..\MarketMind.Models\MarketMind.Data.Models.csproj" />
    <ProjectReference Include="..\MarketMind.Services.Core\MarketMind.Services.Core.csproj" />
    <ProjectReference Include="..\MarketMind.Web.ViewModels\MarketMind.Web.ViewModels.csproj" />
    <ProjectReference Include="..\MarketMindGCommon\MarketMindGCommon.csproj" />
  </ItemGroup>

</Project>
